#Stage1

# pull official base image
FROM node:18.18.2-alpine3.18 as builder

WORKDIR /app
COPY package.json package-lock.json ./
COPY public/ public/
COPY src/ src/
RUN npm ci
RUN npm run build

RUN npm install
COPY src /usr/src/app/src
COPY public /usr/src/app/public
RUN npm run build

#Stage2
FROM nginxinc/nginx-unprivileged
COPY nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]